### ISSUE TITLE
[Bug/Improvement] Some music can't be downloaded / Low Audio Bitrate

### ISSUE THREAD

**Issue by lampi8426** [russkyc/nitefox#2]
Some music can't be downloaded, for example:  https://open.spotify.com/track/3z7J5xDzoPfkpItJr9BxxM?si=9edf008bb28d4ae0. 
Also when I can download the music, it is in 124kbps which is a very strange for music, the song I downloaded is: Wishing Well - Juice WRLD & Samba de Janeiro (from Samba de Amigo) - Player2, NoteBlock.

**Comment by russkyc** [comment]
As this app downloads from youtube instead of spotify directly, it sometimes doesn't accurately find the track. I'll see how the bitrate can improve so I'll keep this issue open for the meantime
